### ISSUE TITLE
Dragon template parse error on startup

### ISSUE THREAD

**Issue by artbnzz** [2008Choco/DragonEggDrop#10]
**Server version : paperspigot 1.12.2**
**Plugin version : DragonEggDrop v1.4.2**

```
[02:23:12] [Server thread/INFO]: [DragonEggDrop] Enabling DragonEggDrop v1.4.2
[02:23:12] [Server thread/ERROR]: Cannot load plugins\DragonEggDrop\dragons\Barrioth.yml
org.bukkit.configuration.InvalidConfigurationException: while parsing a block collection
 in 'string', line 22, column 3:
      - "tellraw %player% {\"text\":\" ... 
      ^
expected <block end>, but found FlowEntry
 in 'string', line 22, column 68:
     ... ongratulations! You have killed",\"color\":\"red\",\"extra\":[{\ ... 
                                         ^

	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:55) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:162) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.configuration.file.FileConfiguration.load(FileConfiguration.java:130) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.configuration.file.YamlConfiguration.loadConfiguration(YamlConfiguration.java:178) [patched_1.12.2.jar:git-Paper-1339]
	at com.ninjaguild.dragoneggdrop.dragon.DragonTemplate.loadTemplates(DragonTemplate.java:483) [DragonEggDrop.jar:?]
	at com.ninjaguild.dragoneggdrop.management.DEDManager.reloadDragonTemplates(DEDManager.java:121) [DragonEggDrop.jar:?]
	at com.ninjaguild.dragoneggdrop.management.DEDManager.<init>(DEDManager.java:52) [DragonEggDrop.jar:?]
	at com.ninjaguild.dragoneggdrop.DragonEggDrop.onEnable(DragonEggDrop.java:135) [DragonEggDrop.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) [patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316) [patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:387) [patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:336) [patched_1.12.2.jar:git-Paper-1339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442) [patched_1.12.2.jar:git-Paper-1339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403) [patched_1.12.2.jar:git-Paper-1339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341) [patched_1.12.2.jar:git-Paper-1339]
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:292) [patched_1.12.2.jar:git-Paper-1339]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616) [patched_1.12.2.jar:git-Paper-1339]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_161]
Caused by: org.yaml.snakeyaml.parser.ParserException: while parsing a block collection
 in 'string', line 22, column 3:
      - "tellraw %player% {\"text\":\" ... 
      ^
expected <block end>, but found FlowEntry
 in 'string', line 22, column 68:
     ... ongratulations! You have killed",\"color\":\"red\",\"extra\":[{\ ... 
                                         ^

	at org.yaml.snakeyaml.parser.ParserImpl$ParseBlockSequenceEntry.produce(ParserImpl.java:515) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.parser.ParserImpl.peekEvent(ParserImpl.java:157) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.parser.ParserImpl.checkEvent(ParserImpl.java:147) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.composeSequenceNode(Composer.java:200) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:152) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.composeValueNode(Composer.java:249) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.composeMappingChildren(Composer.java:240) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.composeMappingNode(Composer.java:228) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.composeNode(Composer.java:154) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.composeDocument(Composer.java:122) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.composer.Composer.getSingleNode(Composer.java:105) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.constructor.BaseConstructor.getSingleData(BaseConstructor.java:140) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.Yaml.loadFromReader(Yaml.java:524) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.yaml.snakeyaml.Yaml.load(Yaml.java:437) ~[patched_1.12.2.jar:git-Paper-1339]
	at org.bukkit.configuration.file.YamlConfiguration.loadFromString(YamlConfiguration.java:53) ~[patched_1.12.2.jar:git-Paper-1339]
	... 18 more```

**Comment by 2008Choco** [comment]
This is a known issue. It will most certainly be fixed after the release of Minecraft 1.13 (do not fret, I will release a version of DragonEggDrop that supports 1.8.x - 1.12.x alongside one that supports 1.13 if you do not plan on updating immediately). Until then, please see [this reply](https://www.spigotmc.org/threads/dragoneggdrop-revival.213400/page-14#post-2828702) on how to temporarily resolve the issue. Thanks!
