### ISSUE TITLE
DragonEggDrop v1.7.0 generated an exception

### ISSUE THREAD

**Issue by Dasco** [2008Choco/DragonEggDrop#23]
[00:55:25] [Server thread/WARN]: [DragonEggDrop] Task #436 for DragonEggDrop v1.7.0 generated an exception
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_212]
	at com.ninjaguild.dragoneggdrop.dragon.DragonLoot.spawnLootFor(DragonLoot.java:504) ~[?:?]
	at com.ninjaguild.dragoneggdrop.utils.runnables.DragonDeathRunnable.run(DragonDeathRunnable.java:136) ~[?:?]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.14.2.jar:git-Paper-65]
	at org.bukkit.craftbukkit.v1_14_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:452) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.b(MinecraftServer.java:1114) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.DedicatedServer.b(DedicatedServer.java:418) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:1060) ~[patched_1.14.2.jar:git-Paper-65]
	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:904) ~[patched_1.14.2.jar:git-Paper-65]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]

Pastebin of the crash: [https://pastebin.com/SpALSvZf](url)
Pastebin of config.yml: [https://pastebin.com/1E1SC5zx](url)
The error started spamming the console right after killing the dragon.
The strange thing is that I killed 2 dragons in a row. After killing the first one, the second one spawned without any problems. After killing the second one, the lightning started spamming the portal without spawning a chest.

If you need more info, ask and you'll receive.

**Comment by Dasco** [comment]
After some testing, I think I found the problem.
Barrioth.yml and all other dragons: [https://pastebin.com/h6rLAzMd](url) 
Could this error have started because I changed these 2 spawn chances to 100% for all dragons ? 
egg-spawn-chance: 100.0
chest-spawn-chance: 100.0

**Comment by 2008Choco** [comment]
This has been resolved alongside the overhaul to the loot system. Will be available in a future release 🙂
