### ISSUE TITLE
DragonEggDrop does not support custom dimensions (data packs)

### ISSUE THREAD

**Issue by istarengwa** [2008Choco/DragonEggDrop#36]
hello, 

- I got an error message since only today when applying the command /dragonspawn start 1s

"An internal error ..."

- I made absolutely no changes between yesterday and today, except the addition of a datapack which adds biomes in the end :

https://www.planetminecraft.com/data-pack/dungeon-now-loading-5-new-dungeons-5-new-bosses/
https://www.planetminecraft.com/data-pack/far-end-ender-expansion-datapack-v0-1/

- When a player joins the end world, a warn spams the console : 

Task #732601 for DragonEggDrop v1.8.2 generated an exception

- and here is the error in the console for the spawn command :

```
[08:50:16 INFO]: Istarengwa issued server command: /dragonspawn start 1s
[08:50:16 ERROR]: null
org.bukkit.command.CommandException: Unhandled exception executing command 'dragonspawn' in plugin DragonEggDrop v1.8.2
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:47) ~[patched_1.16.5.jar:git-Purpur-958]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:172) ~[patched_1.16.5.jar:git-Purpur-958]
        at org.bukkit.craftbukkit.v1_16_R3.CraftServer.dispatchCommand(CraftServer.java:807) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.PlayerConnection.handleCommand(PlayerConnection.java:2074) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.PlayerConnection.c(PlayerConnection.java:1877) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.PlayerConnection.a(PlayerConnection.java:1830) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:47) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.PacketPlayInChat.a(PacketPlayInChat.java:5) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.PlayerConnectionUtils.lambda$ensureMainThread$1(PlayerConnectionUtils.java:43) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.TickTask.run(SourceFile:18) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.MinecraftServer.bb(MinecraftServer.java:1206) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.MinecraftServer.executeNext(MinecraftServer.java:1199) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.IAsyncTaskHandler.executeAll(IAsyncTaskHandler.java:95) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.MinecraftServer.a(MinecraftServer.java:1336) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1009) ~[patched_1.16.5.jar:git-Purpur-958]
        at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:175) ~[patched_1.16.5.jar:git-Purpur-958]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
Caused by: java.lang.NullPointerException
        at com.ninjaguild.dragoneggdrop.tasks.RespawnRunnable.<init>(RespawnRunnable.java:59) ~[?:?]
        at com.ninjaguild.dragoneggdrop.world.EndWorldWrapper.startRespawn(EndWorldWrapper.java:90) ~[?:?]
        at com.ninjaguild.dragoneggdrop.commands.DragonRespawnCmd.onCommand(DragonRespawnCmd.java:109) ~[?:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[patched_1.16.5.jar:git-Purpur-958]
        ... 19 more
```

**Comment by 2008Choco** [comment]
I cannot guarantee the functionality of DragonEggDrop for servers that make use of data packs that add new dimensions. Bukkit assumes the inclusion of only 3 dimensions and whether or not Paper or any derivatives support the addition of new dimensions (which may be the case considering these packs presumably work?) may affect how DragonEggDrop functions.

In short, I'm not sure this is something I can fix. New vanilla dimensions are not technically supported nor considered and this is presumably the reason you're getting this error.

**Comment by eoltw** [comment]
me too

**Comment by 2008Choco** [comment]
I'm going to be closing this issue and chalking it up to CraftBukkit not supporting custom dimension types. As of currently, Bukkit supports only overworld, the nether and end dimensions, not custom dimensions added by 3rd party mods or datapacks. At this current point in time, I am unable to support these types of datapacks.

However, I did make massive progress towards Bukkit itself in supporting custom dimensions by pulling this information directly from the registries and exposing them in the API. There may come a time where this is possible to resolve, but until then I will be closing this as it's not an issue I can resolve with a plugin alone. A change to the server itself is required.
