### ISSUE TITLE
DropsProblem

### ISSUE THREAD

**Issue by CloudeLecaw** [2008Choco/DragonEggDrop#7]
When i setup a ddragon in Spigot 1.12.2 with the attributes - the dragon seems to spawn normal like he should.
when when the dragon dies, then i get an error in the console on droping
`09:18:30] [Server thread/ERROR]: Could not pass event CreatureSpawnEvent to DragonEggDrop v1.4.1
org.bukkit.event.EventException: null
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:499) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:484) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at org.bukkit.craftbukkit.v1_12_R1.event.CraftEventFactory.callCreatureSpawnEvent(CraftEventFactory.java:283) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1042) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.WorldServer.addEntity(WorldServer.java:1112) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.World.addEntity(World.java:1013) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.EnderDragonBattle.m(SourceFile:415) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.EnderDragonBattle.a(SourceFile:273) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.EnumDragonRespawn$4.a(SourceFile:78) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.EnderDragonBattle.b(SourceFile:239) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.WorldProviderTheEnd.s(SourceFile:117) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.WorldServer.tickEntities(WorldServer.java:664) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:817) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_101]
Caused by: java.lang.NullPointerException
	at com.ninjaguild.dragoneggdrop.dragon.DragonTemplate.lambda$0(DragonTemplate.java:432) ~[?:?]
	at java.util.HashMap.forEach(HashMap.java:1288) ~[?:1.8.0_101]
	at com.ninjaguild.dragoneggdrop.dragon.DragonTemplate.applyToBattle(DragonTemplate.java:432) ~[?:?]
	at com.ninjaguild.dragoneggdrop.events.DragonLifeListeners.onCreatureSpawn(DragonLifeListeners.java:72) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_101]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_101]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_101]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_101]
	at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[craftbukkit.jar:git-Spigot-93e20b3-9ab758c]
	... 18 more`

The Result is, that no egg or chests spawns 🥉 
here is an example for setup:
`attributes:
  GENERIC_ARMOR: 10
  GENERIC_ARMOR_TOUGHNESS: 10
  GENERIC_ATTACK_DAMAGE: 10
  GENERIC_ATTACK_SPEED: 5
  GENERIC_FLYING_SPEED: 10
  GENERIC_KNOCKBACK_RESISTANCE: 5
  GENERIC_MAX_HEALTH: 4000
  GENERIC_MOVEMENT_SPEED: 5`
Dont care about the amount of attibutes u edit - the errorresult is the same.
for not i removed all the attributes from my dragons, what results in that is works but then all have the same strengh =( - just different names, and drops

**Comment by CloudeLecaw** [comment]
here the pastebin link aggain to make it better readable:
https://pastebin.com/NJFm6ut2
